name: API Test Workflow
on:
    push:
    branches:
        - main
jobs:
    api_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
    uses: actions/checkout@v2
    - name: Set Up Environment
    run: |
        # Install curl
        sudo apt-get update -qy
        sudo apt-get install -y curl

        # Set the API URL to JSONPlaceholder
        export API_URL="https://jsonplaceholder.typicode.com"
    - name: Test API Connection
    run: |
        # Test the connection to the JSONPlaceholder API
        response=$(curl -s $API_URL/posts/1)

        # Check if the response contains the expected data (e.g., "userId" field)
        if [[ "$response" == *"\"userId\": 1"* ]]; then
        echo "API connection test successful!"
        else
        echo "API connection test failed!"
        exit 1
        fi
    - name: Cleanup
    run: |
        # Clean up any resources or temporary files if needed has context menu Compose